#!/usr/bin/env python2
#-*- coding: utf-8 -*-

import sys
import click

import daemon

@click.command()
@click.option('--serial-device', default='/dev/cuaU1')
@click.option('--pcm-device', default='/tmp/mpd.fifo')
@click.option('--baud', default=57600)
@click.option('--window-size', default=4096)
@click.option('--boot-sleep', default=3.0)
def run_daemon(serial_device, pcm_device, baud, window_size, boot_sleep):

    print "start oink"
    print serial_device
    print baud

    d = daemon.Daemon(serial_device, pcm_device, baud=baud, window_size=window_size, boot_sleep=boot_sleep)
    print "starting daemon."
    d.start()
    exit(0)


if __name__ == '__main__':
    run_daemon()
